// <auto-generated />
using System;
using ActivityCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ActivityCenter.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191213184104_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActivityCenter.Models.Happening", b =>
                {
                    b.Property<int>("HappeningId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedById");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<string>("DurationMetric")
                        .IsRequired();

                    b.Property<DateTime>("HappeningDate");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("Title");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("HappeningId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Happenings");
                });

            modelBuilder.Entity("ActivityCenter.Models.Participation", b =>
                {
                    b.Property<int>("ParticipationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("JoiningActivityId");

                    b.Property<int>("ParticipantId");

                    b.HasKey("ParticipationId");

                    b.HasIndex("JoiningActivityId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("ActivityCenter.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActivityCenter.Models.Happening", b =>
                {
                    b.HasOne("ActivityCenter.Models.User", "CreatedBy")
                        .WithMany("createdPlan")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ActivityCenter.Models.Participation", b =>
                {
                    b.HasOne("ActivityCenter.Models.Happening", "JoiningActivity")
                        .WithMany("ParticipantsList")
                        .HasForeignKey("JoiningActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ActivityCenter.Models.User", "Participant")
                        .WithMany("ActivitiesToAttend")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
